/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=sample/durable-outbox/wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=OutboxEnv sample/durable-outbox/worker-configuration.d.ts` (hash: 9dc8fb3b369757e62e6220fad5118d76)
interface __BaseEnv_OutboxEnv {
  DB: D1Database
  SMTP_HOST: string
  SMTP_PORT: string
  MAIL_FROM: string
  SMTP_USERNAME: string
  SMTP_PASSWORD: string
  OUTBOX_TOKEN: string
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index')
  }
  interface Env extends __BaseEnv_OutboxEnv {}
}
interface OutboxEnv extends __BaseEnv_OutboxEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'SMTP_HOST'
      | 'SMTP_PORT'
      | 'MAIL_FROM'
      | 'SMTP_USERNAME'
      | 'SMTP_PASSWORD'
      | 'OUTBOX_TOKEN'
    >
  > {}
}
