/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=sample/contact-form/wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=ContactEnv sample/contact-form/worker-configuration.d.ts` (hash: 2bce135117f9f4f9ffec545b9976187a)
interface __BaseEnv_ContactEnv {
  DB: D1Database
  SMTP_HOST: string
  SMTP_PORT: string
  MAIL_FROM: string
  PUBLIC_ORIGIN: string
  MAIL_TO: string
  TURNSTILE_SITE_KEY: string
  SMTP_USERNAME: string
  SMTP_PASSWORD: string
  TURNSTILE_SECRET_KEY: string
  RATE_LIMIT_SECRET: string
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index')
  }
  interface Env extends __BaseEnv_ContactEnv {}
}
interface ContactEnv extends __BaseEnv_ContactEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'SMTP_HOST'
      | 'SMTP_PORT'
      | 'MAIL_FROM'
      | 'PUBLIC_ORIGIN'
      | 'MAIL_TO'
      | 'TURNSTILE_SITE_KEY'
      | 'SMTP_USERNAME'
      | 'SMTP_PASSWORD'
      | 'TURNSTILE_SECRET_KEY'
      | 'RATE_LIMIT_SECRET'
    >
  > {}
}
